import Head from "next/head";
import Image from "next/image";
import { Flex, Tabs, TabList, TabPanels, Tab, TabPanel } from '@chakra-ui/react'
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import TransactionsTable from "../../components/transactions/trnxTable";
import { useFetchTopPools } from "../../hooks/useFetchTopPools";
import { useFetchTokens } from "../../hooks/useFetchTokens";
import { useFetchTransactions } from "../../hooks/useFetchTransactions";

import OverView from "../../components/overView";
import PageLayout from "../../components/pageLayout";

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { topPools, poolsLoading, refetchTopPools } = useFetchTopPools();
  const { tokens, isLoading, refetchTokens } = useFetchTokens();
  const { transactions, trnxLoading} = useFetchTransactions();

    console.log("tokens", tokens);

  return (
    <>
      <Head>
        <title>Common Visualizer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <PageLayout topPools={topPools} poolsLoading={poolsLoading} tokens={tokens} />
    </>
  );
}
